version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
   ignore:
      - dependency-name: "ethers*" 
      versions: ["6.x"]
